// Code meanings, generated from the Mac app's database. Do not edit by hand.
enum CodeData {
    // generic
    static let generic: [String: String] = [
        "B0001": "Driver frontal airbag stage 1 deployment control",
        "B0002": "Driver frontal airbag stage 2 deployment control",
        "C0035": "Left front wheel speed sensor circuit",
        "C0040": "Right front wheel speed sensor circuit",
        "C0045": "Left rear wheel speed sensor circuit",
        "C0050": "Right rear wheel speed sensor circuit",
        "P0010": "Intake camshaft position actuator circuit (bank 1)",
        "P0011": "Intake camshaft timing over-advanced or system performance (bank 1)",
        "P0012": "Intake camshaft timing over-retarded (bank 1)",
        "P0013": "Exhaust camshaft position actuator circuit (bank 1)",
        "P0014": "Exhaust camshaft timing over-advanced or system performance (bank 1)",
        "P0015": "Exhaust camshaft timing over-retarded (bank 1)",
        "P0016": "Crankshaft/camshaft position correlation (bank 1, sensor A)",
        "P0017": "Crankshaft/camshaft position correlation (bank 1, sensor B)",
        "P0018": "Crankshaft/camshaft position correlation (bank 2, sensor A)",
        "P0019": "Crankshaft/camshaft position correlation (bank 2, sensor B)",
        "P0020": "Intake camshaft position actuator circuit (bank 2)",
        "P0021": "Intake camshaft timing over-advanced or system performance (bank 2)",
        "P0022": "Intake camshaft timing over-retarded (bank 2)",
        "P0030": "O2 sensor heater control circuit (bank 1, sensor 1)",
        "P0031": "O2 sensor heater control circuit low (bank 1, sensor 1)",
        "P0032": "O2 sensor heater control circuit high (bank 1, sensor 1)",
        "P0036": "O2 sensor heater control circuit (bank 1, sensor 2)",
        "P0037": "O2 sensor heater control circuit low (bank 1, sensor 2)",
        "P0038": "O2 sensor heater control circuit high (bank 1, sensor 2)",
        "P0050": "O2 sensor heater control circuit (bank 2, sensor 1)",
        "P0051": "O2 sensor heater control circuit low (bank 2, sensor 1)",
        "P0052": "O2 sensor heater control circuit high (bank 2, sensor 1)",
        "P0056": "O2 sensor heater control circuit (bank 2, sensor 2)",
        "P0057": "O2 sensor heater control circuit low (bank 2, sensor 2)",
        "P0058": "O2 sensor heater control circuit high (bank 2, sensor 2)",
        "P0087": "Fuel rail/system pressure too low",
        "P0088": "Fuel rail/system pressure too high",
        "P0089": "Fuel pressure regulator performance",
        "P0093": "Fuel system large leak detected",
        "P0100": "Mass air flow (MAF) sensor circuit malfunction",
        "P0101": "Mass air flow (MAF) sensor circuit range/performance",
        "P0102": "Mass air flow (MAF) sensor circuit low input",
        "P0103": "Mass air flow (MAF) sensor circuit high input",
        "P0104": "Mass air flow (MAF) sensor circuit intermittent",
        "P0105": "Manifold absolute pressure (MAP) / barometric pressure sensor circuit malfunction",
        "P0106": "Manifold absolute pressure (MAP) / barometric pressure sensor circuit range/performance",
        "P0107": "Manifold absolute pressure (MAP) / barometric pressure sensor circuit low input",
        "P0108": "Manifold absolute pressure (MAP) / barometric pressure sensor circuit high input",
        "P0109": "Manifold absolute pressure (MAP) / barometric pressure sensor circuit intermittent",
        "P0110": "Intake air temperature (IAT) sensor circuit malfunction",
        "P0111": "Intake air temperature (IAT) sensor circuit range/performance",
        "P0112": "Intake air temperature (IAT) sensor circuit low input",
        "P0113": "Intake air temperature (IAT) sensor circuit high input",
        "P0114": "Intake air temperature (IAT) sensor circuit intermittent",
        "P0115": "Engine coolant temperature (ECT) sensor circuit malfunction",
        "P0116": "Engine coolant temperature (ECT) sensor circuit range/performance",
        "P0117": "Engine coolant temperature (ECT) sensor circuit low input",
        "P0118": "Engine coolant temperature (ECT) sensor circuit high input",
        "P0119": "Engine coolant temperature (ECT) sensor circuit intermittent",
        "P0120": "Throttle/pedal position sensor A circuit malfunction",
        "P0121": "Throttle/pedal position sensor A circuit range/performance",
        "P0122": "Throttle/pedal position sensor A circuit low input",
        "P0123": "Throttle/pedal position sensor A circuit high input",
        "P0124": "Throttle/pedal position sensor A circuit intermittent",
        "P0125": "Insufficient coolant temperature for closed-loop fuel control",
        "P0128": "Coolant temperature below thermostat regulating temperature",
        "P0130": "O2 sensor circuit malfunction (bank 1, sensor 1)",
        "P0131": "O2 sensor circuit low voltage (bank 1, sensor 1)",
        "P0132": "O2 sensor circuit high voltage (bank 1, sensor 1)",
        "P0133": "O2 sensor circuit slow response (bank 1, sensor 1)",
        "P0134": "O2 sensor circuit no activity detected (bank 1, sensor 1)",
        "P0135": "O2 sensor heater circuit malfunction (bank 1, sensor 1)",
        "P0136": "O2 sensor circuit malfunction (bank 1, sensor 2)",
        "P0137": "O2 sensor circuit low voltage (bank 1, sensor 2)",
        "P0138": "O2 sensor circuit high voltage (bank 1, sensor 2)",
        "P0139": "O2 sensor circuit slow response (bank 1, sensor 2)",
        "P0140": "O2 sensor circuit no activity detected (bank 1, sensor 2)",
        "P0141": "O2 sensor heater circuit malfunction (bank 1, sensor 2)",
        "P0142": "O2 sensor circuit malfunction (bank 1, sensor 3)",
        "P0143": "O2 sensor circuit low voltage (bank 1, sensor 3)",
        "P0144": "O2 sensor circuit high voltage (bank 1, sensor 3)",
        "P0145": "O2 sensor circuit slow response (bank 1, sensor 3)",
        "P0146": "O2 sensor circuit no activity detected (bank 1, sensor 3)",
        "P0147": "O2 sensor heater circuit malfunction (bank 1, sensor 3)",
        "P0150": "O2 sensor circuit malfunction (bank 2, sensor 1)",
        "P0151": "O2 sensor circuit low voltage (bank 2, sensor 1)",
        "P0152": "O2 sensor circuit high voltage (bank 2, sensor 1)",
        "P0153": "O2 sensor circuit slow response (bank 2, sensor 1)",
        "P0154": "O2 sensor circuit no activity detected (bank 2, sensor 1)",
        "P0155": "O2 sensor heater circuit malfunction (bank 2, sensor 1)",
        "P0156": "O2 sensor circuit malfunction (bank 2, sensor 2)",
        "P0157": "O2 sensor circuit low voltage (bank 2, sensor 2)",
        "P0158": "O2 sensor circuit high voltage (bank 2, sensor 2)",
        "P0159": "O2 sensor circuit slow response (bank 2, sensor 2)",
        "P0160": "O2 sensor circuit no activity detected (bank 2, sensor 2)",
        "P0161": "O2 sensor heater circuit malfunction (bank 2, sensor 2)",
        "P0162": "O2 sensor circuit malfunction (bank 2, sensor 3)",
        "P0163": "O2 sensor circuit low voltage (bank 2, sensor 3)",
        "P0164": "O2 sensor circuit high voltage (bank 2, sensor 3)",
        "P0165": "O2 sensor circuit slow response (bank 2, sensor 3)",
        "P0166": "O2 sensor circuit no activity detected (bank 2, sensor 3)",
        "P0167": "O2 sensor heater circuit malfunction (bank 2, sensor 3)",
        "P0170": "Fuel trim malfunction (bank 1)",
        "P0171": "System too lean (bank 1)",
        "P0172": "System too rich (bank 1)",
        "P0173": "Fuel trim malfunction (bank 2)",
        "P0174": "System too lean (bank 2)",
        "P0175": "System too rich (bank 2)",
        "P0180": "Fuel temperature sensor A circuit malfunction",
        "P0181": "Fuel temperature sensor A circuit range/performance",
        "P0182": "Fuel temperature sensor A circuit low input",
        "P0183": "Fuel temperature sensor A circuit high input",
        "P0184": "Fuel temperature sensor A circuit intermittent",
        "P0190": "Fuel rail pressure sensor circuit malfunction",
        "P0191": "Fuel rail pressure sensor circuit range/performance",
        "P0192": "Fuel rail pressure sensor circuit low input",
        "P0193": "Fuel rail pressure sensor circuit high input",
        "P0194": "Fuel rail pressure sensor circuit intermittent",
        "P0195": "Engine oil temperature sensor circuit malfunction",
        "P0196": "Engine oil temperature sensor circuit range/performance",
        "P0197": "Engine oil temperature sensor circuit low input",
        "P0198": "Engine oil temperature sensor circuit high input",
        "P0199": "Engine oil temperature sensor circuit intermittent",
        "P0200": "Fuel injector circuit malfunction",
        "P0201": "Fuel injector circuit/open - cylinder 1",
        "P0202": "Fuel injector circuit/open - cylinder 2",
        "P0203": "Fuel injector circuit/open - cylinder 3",
        "P0204": "Fuel injector circuit/open - cylinder 4",
        "P0205": "Fuel injector circuit/open - cylinder 5",
        "P0206": "Fuel injector circuit/open - cylinder 6",
        "P0207": "Fuel injector circuit/open - cylinder 7",
        "P0208": "Fuel injector circuit/open - cylinder 8",
        "P0209": "Fuel injector circuit/open - cylinder 9",
        "P0210": "Fuel injector circuit/open - cylinder 10",
        "P0211": "Fuel injector circuit/open - cylinder 11",
        "P0212": "Fuel injector circuit/open - cylinder 12",
        "P0217": "Engine overtemperature condition",
        "P0219": "Engine overspeed condition",
        "P0220": "Throttle/pedal position sensor B circuit malfunction",
        "P0221": "Throttle/pedal position sensor B circuit range/performance",
        "P0222": "Throttle/pedal position sensor B circuit low input",
        "P0223": "Throttle/pedal position sensor B circuit high input",
        "P0224": "Throttle/pedal position sensor B circuit intermittent",
        "P0230": "Fuel pump primary circuit malfunction",
        "P0231": "Fuel pump secondary circuit low",
        "P0232": "Fuel pump secondary circuit high",
        "P0234": "Turbocharger/supercharger overboost condition",
        "P0299": "Turbocharger/supercharger underboost condition",
        "P0300": "Random/multiple cylinder misfire detected",
        "P0301": "Cylinder 1 misfire detected",
        "P0302": "Cylinder 2 misfire detected",
        "P0303": "Cylinder 3 misfire detected",
        "P0304": "Cylinder 4 misfire detected",
        "P0305": "Cylinder 5 misfire detected",
        "P0306": "Cylinder 6 misfire detected",
        "P0307": "Cylinder 7 misfire detected",
        "P0308": "Cylinder 8 misfire detected",
        "P0309": "Cylinder 9 misfire detected",
        "P0310": "Cylinder 10 misfire detected",
        "P0311": "Cylinder 11 misfire detected",
        "P0312": "Cylinder 12 misfire detected",
        "P0325": "Knock sensor 1 (bank 1) circuit malfunction",
        "P0326": "Knock sensor 1 (bank 1) circuit range/performance",
        "P0327": "Knock sensor 1 (bank 1) circuit low input",
        "P0328": "Knock sensor 1 (bank 1) circuit high input",
        "P0329": "Knock sensor 1 (bank 1) circuit intermittent",
        "P0330": "Knock sensor 2 (bank 2) circuit malfunction",
        "P0331": "Knock sensor 2 (bank 2) circuit range/performance",
        "P0332": "Knock sensor 2 (bank 2) circuit low input",
        "P0333": "Knock sensor 2 (bank 2) circuit high input",
        "P0334": "Knock sensor 2 (bank 2) circuit intermittent",
        "P0335": "Crankshaft position sensor A circuit malfunction",
        "P0336": "Crankshaft position sensor A circuit range/performance",
        "P0337": "Crankshaft position sensor A circuit low input",
        "P0338": "Crankshaft position sensor A circuit high input",
        "P0339": "Crankshaft position sensor A circuit intermittent",
        "P0340": "Camshaft position sensor A (bank 1) circuit malfunction",
        "P0341": "Camshaft position sensor A (bank 1) circuit range/performance",
        "P0342": "Camshaft position sensor A (bank 1) circuit low input",
        "P0343": "Camshaft position sensor A (bank 1) circuit high input",
        "P0344": "Camshaft position sensor A (bank 1) circuit intermittent",
        "P0345": "Camshaft position sensor A (bank 2) circuit malfunction",
        "P0346": "Camshaft position sensor A (bank 2) circuit range/performance",
        "P0347": "Camshaft position sensor A (bank 2) circuit low input",
        "P0348": "Camshaft position sensor A (bank 2) circuit high input",
        "P0349": "Camshaft position sensor A (bank 2) circuit intermittent",
        "P0350": "Ignition coil primary/secondary circuit malfunction",
        "P0351": "Ignition coil A (cylinder 1) primary/secondary circuit",
        "P0352": "Ignition coil B (cylinder 2) primary/secondary circuit",
        "P0353": "Ignition coil C (cylinder 3) primary/secondary circuit",
        "P0354": "Ignition coil D (cylinder 4) primary/secondary circuit",
        "P0355": "Ignition coil E (cylinder 5) primary/secondary circuit",
        "P0356": "Ignition coil F (cylinder 6) primary/secondary circuit",
        "P0357": "Ignition coil G (cylinder 7) primary/secondary circuit",
        "P0358": "Ignition coil H (cylinder 8) primary/secondary circuit",
        "P0359": "Ignition coil I (cylinder 9) primary/secondary circuit",
        "P0360": "Ignition coil J (cylinder 10) primary/secondary circuit",
        "P0361": "Ignition coil K (cylinder 11) primary/secondary circuit",
        "P0362": "Ignition coil L (cylinder 12) primary/secondary circuit",
        "P0365": "Camshaft position sensor B circuit (bank 1)",
        "P0366": "Camshaft position sensor B circuit range/performance (bank 1)",
        "P0380": "Glow plug/heater circuit A malfunction",
        "P0400": "Exhaust gas recirculation (EGR) flow malfunction",
        "P0401": "EGR flow insufficient detected",
        "P0402": "EGR flow excessive detected",
        "P0403": "EGR control circuit malfunction",
        "P0404": "EGR control circuit range/performance",
        "P0405": "EGR sensor A circuit low",
        "P0406": "EGR sensor A circuit high",
        "P0410": "Secondary air injection system malfunction",
        "P0411": "Secondary air injection system incorrect flow detected",
        "P0412": "Secondary air injection switching valve A circuit",
        "P0418": "Secondary air injection pump relay A circuit",
        "P0420": "Catalyst system efficiency below threshold (bank 1)",
        "P0421": "Warm-up catalyst efficiency below threshold (bank 1)",
        "P0430": "Catalyst system efficiency below threshold (bank 2)",
        "P0431": "Warm-up catalyst efficiency below threshold (bank 2)",
        "P0440": "Evaporative emission (EVAP) system malfunction",
        "P0441": "EVAP system incorrect purge flow",
        "P0442": "EVAP system small leak detected",
        "P0443": "EVAP purge control valve circuit malfunction",
        "P0444": "EVAP purge control valve circuit open",
        "P0445": "EVAP purge control valve circuit shorted",
        "P0446": "EVAP vent control circuit malfunction",
        "P0447": "EVAP vent control circuit open",
        "P0448": "EVAP vent control circuit shorted",
        "P0449": "EVAP vent valve/solenoid circuit malfunction",
        "P0450": "EVAP pressure sensor malfunction",
        "P0451": "EVAP pressure sensor range/performance",
        "P0452": "EVAP pressure sensor low input",
        "P0453": "EVAP pressure sensor high input",
        "P0454": "EVAP pressure sensor intermittent",
        "P0455": "EVAP system large leak detected",
        "P0456": "EVAP system very small leak detected",
        "P0457": "EVAP system leak detected (fuel cap loose/off)",
        "P0460": "Fuel level sensor circuit malfunction",
        "P0461": "Fuel level sensor circuit range/performance",
        "P0462": "Fuel level sensor circuit low input",
        "P0463": "Fuel level sensor circuit high input",
        "P0464": "Fuel level sensor circuit intermittent",
        "P0480": "Cooling fan 1 control circuit malfunction",
        "P0481": "Cooling fan 2 control circuit malfunction",
        "P0500": "Vehicle speed sensor malfunction",
        "P0501": "Vehicle speed sensor range/performance",
        "P0502": "Vehicle speed sensor low input",
        "P0503": "Vehicle speed sensor intermittent/erratic/high",
        "P0505": "Idle air control system malfunction",
        "P0506": "Idle control system RPM lower than expected",
        "P0507": "Idle control system RPM higher than expected",
        "P0520": "Engine oil pressure sensor/switch circuit malfunction",
        "P0521": "Engine oil pressure sensor/switch circuit range/performance",
        "P0522": "Engine oil pressure sensor/switch circuit low voltage",
        "P0523": "Engine oil pressure sensor/switch circuit high voltage",
        "P0524": "Engine oil pressure too low",
        "P0530": "A/C refrigerant pressure sensor circuit malfunction",
        "P0531": "A/C refrigerant pressure sensor circuit range/performance",
        "P0532": "A/C refrigerant pressure sensor circuit low input",
        "P0533": "A/C refrigerant pressure sensor circuit high input",
        "P0560": "System voltage malfunction",
        "P0562": "System voltage low",
        "P0563": "System voltage high",
        "P0571": "Brake switch A circuit malfunction",
        "P0600": "Serial communication link malfunction",
        "P0601": "Internal control module memory checksum error",
        "P0602": "Control module programming error",
        "P0603": "Internal control module keep-alive memory (KAM) error",
        "P0604": "Internal control module RAM error",
        "P0605": "Internal control module ROM error",
        "P0606": "Control module processor fault",
        "P0607": "Control module performance",
        "P0620": "Generator (alternator) control circuit malfunction",
        "P0621": "Generator lamp 'L' terminal circuit malfunction",
        "P0622": "Generator field 'F' terminal circuit malfunction",
        "P0627": "Fuel pump control circuit open",
        "P0641": "Sensor reference voltage A circuit open",
        "P0651": "Sensor reference voltage B circuit open",
        "P0685": "ECM/PCM power relay control circuit open",
        "P0700": "Transmission control system malfunction (TCM has requested the check engine light)",
        "P0705": "Transmission range sensor (PRNDL input) circuit malfunction",
        "P0706": "Transmission range sensor (PRNDL input) circuit range/performance",
        "P0707": "Transmission range sensor (PRNDL input) circuit low input",
        "P0708": "Transmission range sensor (PRNDL input) circuit high input",
        "P0709": "Transmission range sensor (PRNDL input) circuit intermittent",
        "P0710": "Transmission fluid temperature sensor circuit malfunction",
        "P0711": "Transmission fluid temperature sensor circuit range/performance",
        "P0712": "Transmission fluid temperature sensor circuit low input",
        "P0713": "Transmission fluid temperature sensor circuit high input",
        "P0714": "Transmission fluid temperature sensor circuit intermittent",
        "P0715": "Input/turbine speed sensor circuit malfunction",
        "P0716": "Input/turbine speed sensor circuit range/performance",
        "P0717": "Input/turbine speed sensor circuit no signal",
        "P0718": "Input/turbine speed sensor circuit intermittent",
        "P0720": "Output speed sensor circuit malfunction",
        "P0721": "Output speed sensor circuit range/performance",
        "P0722": "Output speed sensor circuit no signal",
        "P0723": "Output speed sensor circuit intermittent",
        "P0730": "Incorrect gear ratio",
        "P0731": "Gear 1 incorrect ratio",
        "P0732": "Gear 2 incorrect ratio",
        "P0733": "Gear 3 incorrect ratio",
        "P0734": "Gear 4 incorrect ratio",
        "P0735": "Gear 5 incorrect ratio",
        "P0736": "Reverse incorrect ratio",
        "P0740": "Torque converter clutch circuit malfunction",
        "P0741": "Torque converter clutch circuit performance or stuck off",
        "P0742": "Torque converter clutch circuit stuck on",
        "P0743": "Torque converter clutch circuit electrical",
        "P0744": "Torque converter clutch circuit intermittent",
        "P0750": "Shift solenoid A malfunction",
        "P0751": "Shift solenoid A performance or stuck off",
        "P0752": "Shift solenoid A stuck on",
        "P0753": "Shift solenoid A electrical",
        "P0754": "Shift solenoid A intermittent",
        "P0755": "Shift solenoid B malfunction",
        "P0756": "Shift solenoid B performance or stuck off",
        "P0757": "Shift solenoid B stuck on",
        "P0758": "Shift solenoid B electrical",
        "P0759": "Shift solenoid B intermittent",
        "P0760": "Shift solenoid C malfunction",
        "P0761": "Shift solenoid C performance or stuck off",
        "P0762": "Shift solenoid C stuck on",
        "P0763": "Shift solenoid C electrical",
        "P0764": "Shift solenoid C intermittent",
        "P0765": "Shift solenoid D malfunction",
        "P0766": "Shift solenoid D performance or stuck off",
        "P0767": "Shift solenoid D stuck on",
        "P0768": "Shift solenoid D electrical",
        "P0769": "Shift solenoid D intermittent",
        "P0770": "Shift solenoid E malfunction",
        "P0771": "Shift solenoid E performance or stuck off",
        "P0772": "Shift solenoid E stuck on",
        "P0773": "Shift solenoid E electrical",
        "P0774": "Shift solenoid E intermittent",
        "P0841": "Transmission fluid pressure sensor/switch A circuit range/performance",
        "P0850": "Park/neutral switch input circuit",
        "P0868": "Transmission fluid pressure low",
        "P0A80": "Replace hybrid battery pack",
        "P0AA6": "Hybrid battery voltage system isolation fault",
        "P2002": "Diesel particulate filter efficiency below threshold (bank 1)",
        "P2004": "Intake manifold runner control stuck open (bank 1)",
        "P2096": "Post-catalyst fuel trim system too lean (bank 1)",
        "P2097": "Post-catalyst fuel trim system too rich (bank 1)",
        "P2098": "Post-catalyst fuel trim system too lean (bank 2)",
        "P2099": "Post-catalyst fuel trim system too rich (bank 2)",
        "P20EE": "SCR NOx catalyst efficiency below threshold (bank 1)",
        "P2101": "Throttle actuator control motor circuit range/performance",
        "P2111": "Throttle actuator control system stuck open",
        "P2112": "Throttle actuator control system stuck closed",
        "P2119": "Throttle actuator control throttle body range/performance",
        "P2135": "Throttle/pedal position sensor A/B voltage correlation",
        "P2138": "Throttle/pedal position sensor D/E voltage correlation",
        "P2187": "System too lean at idle (bank 1)",
        "P2188": "System too rich at idle (bank 1)",
        "P2189": "System too lean at idle (bank 2)",
        "P2190": "System too rich at idle (bank 2)",
        "P2195": "O2 sensor signal biased/stuck lean (bank 1, sensor 1)",
        "P2196": "O2 sensor signal biased/stuck rich (bank 1, sensor 1)",
        "P2197": "O2 sensor signal biased/stuck lean (bank 2, sensor 1)",
        "P2198": "O2 sensor signal biased/stuck rich (bank 2, sensor 1)",
        "P2270": "O2 sensor signal biased/stuck lean (bank 1, sensor 2)",
        "P2271": "O2 sensor signal biased/stuck rich (bank 1, sensor 2)",
        "P2272": "O2 sensor signal biased/stuck lean (bank 2, sensor 2)",
        "P2273": "O2 sensor signal biased/stuck rich (bank 2, sensor 2)",
        "P2463": "Diesel particulate filter soot accumulation",
        "P2610": "ECM/PCM internal engine-off timer performance",
        "P2A00": "O2 sensor circuit range/performance (bank 1, sensor 1)",
        "P2A03": "O2 sensor circuit range/performance (bank 2, sensor 1)",
        "U0001": "High-speed CAN communication bus",
        "U0073": "Control module communication bus A off",
        "U0100": "Lost communication with ECM/PCM 'A'",
        "U0101": "Lost communication with TCM (transmission)",
        "U0121": "Lost communication with ABS control module",
        "U0140": "Lost communication with body control module (BCM)",
        "U0151": "Lost communication with restraints (airbag) control module",
        "U0155": "Lost communication with instrument panel cluster",
        "U0164": "Lost communication with HVAC control module",
        "U0401": "Invalid data received from ECM/PCM 'A'",
        "U0415": "Invalid data received from ABS control module",
    ]

    // ford
    static let ford: [String: String] = [
        "B1318": "Battery voltage low",
        "B1342": "Module has an internal fault",
        "B1869": "Airbag warning light circuit open",
        "B1870": "Airbag warning light circuit shorted to battery",
        "B1921": "Airbag module ground circuit open",
        "B1932": "Driver airbag circuit open (often the clock spring behind the steering wheel)",
        "B2477": "Module configuration (set-up) fault",
        "C1095": "ABS pump motor circuit fault",
        "C1096": "ABS pump motor circuit open",
        "C1145": "Right front wheel speed sensor circuit fault",
        "C1155": "Left front wheel speed sensor circuit fault",
        "C1165": "Right rear wheel speed sensor circuit fault",
        "C1175": "Left rear wheel speed sensor circuit fault",
        "C1185": "ABS power relay output circuit fault",
        "C1194": "Left front ABS outlet valve circuit fault",
        "C1198": "Left front ABS inlet valve circuit fault",
        "C1210": "Right front ABS outlet valve circuit fault",
        "C1214": "Right front ABS inlet valve circuit fault",
        "C1222": "Wheel speeds don't match each other",
        "C1233": "Left front wheel speed signal missing",
        "C1234": "Right front wheel speed signal missing",
        "C1235": "Right rear wheel speed signal missing",
        "C1236": "Left rear wheel speed signal missing",
        "C1242": "Left rear ABS outlet valve circuit fault",
        "C1246": "Left rear ABS inlet valve circuit fault",
        "C1250": "Right rear ABS outlet valve circuit fault",
        "C1254": "Right rear ABS inlet valve circuit fault",
        "P1000": "Self-tests not finished yet since the last time codes were cleared (not a fault)",
        "P1001": "Engine-running self-test couldn't finish",
        "P1100": "Mass airflow (MAF) sensor signal comes and goes",
        "P1101": "Mass airflow (MAF) sensor reading out of range during self-test",
        "P1112": "Intake air temperature sensor signal comes and goes",
        "P1116": "Coolant temperature sensor reading out of range during self-test",
        "P1117": "Coolant temperature sensor signal comes and goes",
        "P1120": "Throttle position sensor reading too low",
        "P1121": "Throttle position sensor doesn't agree with the airflow sensor",
        "P1124": "Throttle position sensor out of range during self-test",
        "P1125": "Throttle position sensor signal comes and goes",
        "P1130": "Front oxygen sensor not switching, fuel adjustment at its limit (bank 1)",
        "P1131": "Front oxygen sensor not switching, reads lean (bank 1)",
        "P1132": "Front oxygen sensor not switching, reads rich (bank 1)",
        "P1150": "Front oxygen sensor not switching, fuel adjustment at its limit (bank 2)",
        "P1151": "Front oxygen sensor not switching, reads lean (bank 2)",
        "P1152": "Front oxygen sensor not switching, reads rich (bank 2)",
        "P1211": "Diesel injection control pressure higher or lower than it should be",
        "P1233": "Fuel pump driver module turned off or not answering",
        "P1235": "Fuel pump control out of range",
        "P1237": "Fuel pump secondary circuit fault",
        "P1260": "Anti-theft (PATS) blocked the engine: key not recognized",
        "P1270": "Engine speed or vehicle speed limiter reached",
        "P1280": "Diesel injection control pressure sensor reading too low",
        "P1281": "Diesel injection control pressure sensor reading too high",
        "P1285": "Cylinder head too hot",
        "P1288": "Cylinder head temperature sensor out of range during self-test",
        "P1289": "Cylinder head temperature sensor circuit reading high",
        "P1290": "Cylinder head temperature sensor circuit reading low",
        "P1299": "Engine overheat protection is active (cylinder head too hot)",
        "P1316": "Diesel injector driver module has its own fault codes stored",
        "P1351": "Ignition diagnostic monitor signal missing",
        "P1400": "EGR pressure sensor (DPFE) circuit reading low",
        "P1401": "EGR pressure sensor (DPFE) circuit reading high",
        "P1405": "EGR pressure sensor (DPFE) upstream hose off or plugged",
        "P1406": "EGR pressure sensor (DPFE) downstream hose off or plugged",
        "P1408": "EGR flow out of range during self-test",
        "P1409": "EGR vacuum regulator solenoid circuit fault",
        "P1450": "Fuel tank vacuum can't build up (EVAP)",
        "P1451": "EVAP canister vent solenoid circuit fault",
        "P1460": "Wide-open-throttle A/C cut-off relay circuit fault",
        "P1464": "A/C request signal out of range during self-test",
        "P1474": "Low-speed cooling fan control circuit fault",
        "P1479": "High-speed cooling fan control circuit fault",
        "P1500": "Vehicle speed sensor signal comes and goes",
        "P1501": "Vehicle speed sensor out of range during self-test",
        "P1504": "Idle air control valve circuit fault",
        "P1505": "Idle air control at its adjustment limit",
        "P1506": "Idle speed higher than it should be",
        "P1507": "Idle speed lower than it should be",
        "P1516": "Intake manifold runner control (bank 1) not working right",
        "P1517": "Intake manifold runner control (bank 2) not working right",
        "P1518": "Intake manifold runner control stuck open",
        "P1549": "Intake manifold tuning valve fault",
        "P1605": "Engine computer memory (keep-alive) test error",
        "P1635": "Tire size or axle ratio setting out of range",
        "P1639": "Vehicle ID (build information) missing or corrupted in the engine computer",
        "P1650": "Power steering pressure switch out of range during self-test",
        "P1651": "Power steering pressure switch signal fault",
        "P1700": "Transmission fault, transmission in limp mode",
        "P1703": "Brake pedal switch out of range during self-test",
        "P1705": "Transmission range (gear position) sensor out of range during self-test",
        "P1711": "Transmission fluid temperature sensor out of range during self-test",
        "P1714": "Shift solenoid A not working right",
        "P1715": "Shift solenoid B not working right",
        "P1728": "Transmission slipping",
        "P1729": "4x4 low switch fault",
        "P1740": "Torque converter clutch solenoid not working right",
        "P1744": "Torque converter clutch not locking up as it should",
        "P1746": "Transmission pressure control (EPC) solenoid circuit open",
        "P1747": "Transmission pressure control (EPC) solenoid circuit shorted",
        "P1780": "Overdrive cancel switch out of range during self-test",
        "P1781": "4x4 low switch out of range during self-test",
        "P1783": "Transmission too hot",
        "U1262": "Module network (SCP) communication fault",
        "U1900": "Module network (CAN) communication fault, messages not received",
    ]

    // gm
    static let gm: [String: String] = [
        "B0051": "Airbag deployment commanded (crash data stored, module usually needs replacing)",
        "B1000": "Module has an internal fault",
        "B1001": "Module options set-up fault",
        "C0110": "ABS pump motor circuit fault",
        "C0121": "ABS valve relay circuit fault",
        "C0161": "ABS brake switch circuit fault",
        "C0242": "Engine computer reported a traction control fault",
        "C0265": "ABS module relay circuit fault",
        "C0267": "ABS pump motor circuit open or shorted",
        "C0550": "ABS module internal fault",
        "C0561": "ABS system turned off because of a stored fault",
        "C0896": "ABS module supply voltage out of range",
        "P1101": "Intake airflow system performance (air leak or airflow sensor problem)",
        "P1125": "Accelerator pedal position system fault",
        "P1133": "Front oxygen sensor not switching enough (bank 1)",
        "P1134": "Front oxygen sensor switching too slowly (bank 1)",
        "P1153": "Front oxygen sensor not switching enough (bank 2)",
        "P1154": "Front oxygen sensor switching too slowly (bank 2)",
        "P1258": "Engine overheating, protection mode active",
        "P1345": "Crankshaft and camshaft sensor signals don't line up (timing)",
        "P1351": "Ignition control circuit voltage high",
        "P1361": "Ignition control circuit voltage low",
        "P1380": "Misfire detected, rough-road data from the ABS not available",
        "P1381": "Misfire detected, no data from the ABS computer",
        "P1406": "EGR valve position sensor circuit fault",
        "P1415": "Secondary air injection system fault (bank 1)",
        "P1416": "Secondary air injection system fault (bank 2)",
        "P1441": "EVAP system flow when it should be off (purge valve leaking)",
        "P1508": "Idle speed too low, idle air control not responding",
        "P1509": "Idle speed too high, idle air control not responding",
        "P1516": "Electronic throttle body position doesn't match what was commanded",
        "P1626": "Anti-theft fuel-enable signal not received",
        "P1630": "Anti-theft system is in learn mode",
        "P1631": "Anti-theft start-enable signal not correct",
        "P1635": "5-volt sensor supply circuit fault",
        "P1639": "Second 5-volt sensor supply circuit fault",
        "P1682": "Ignition switch power circuit 2 fault",
        "P1810": "Transmission fluid pressure switch circuit fault",
        "P1860": "Torque converter clutch solenoid circuit fault",
        "P1870": "Transmission slipping (worn internal part)",
        "U1000": "Module network (Class 2) communication fault",
        "U1016": "Lost communication with the engine computer",
        "U1041": "Lost communication with the ABS module",
        "U1064": "Lost communication with the body control module",
        "U1088": "Lost communication with the airbag module",
        "U1300": "Module network (Class 2) wire shorted to ground",
        "U1301": "Module network (Class 2) wire shorted to battery voltage",
    ]
}
